// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go_gapic. DO NOT EDIT.


package echoclient

import (
	"context"
	"fmt"
	"log/slog"
	"math"
	"net/url"
	"time"

	"cloud.google.com/go/longrunning"
	lroauto "cloud.google.com/go/longrunning/autogen"
	longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	gax "github.com/googleapis/gax-go/v2"
	echopb "github.com/salrashid123/gapic_generator_grpc_helloworld/echo"
	"google.golang.org/api/option"
	"google.golang.org/api/option/internaloption"
	gtransport "google.golang.org/api/transport/grpc"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
)

var newEchoServerClientHook clientHook

// EchoServerCallOptions contains the retry settings for each method of EchoServerClient.
type EchoServerCallOptions struct {
	SayHello []gax.CallOption
	SayHelloLRO []gax.CallOption
}

func defaultEchoServerGRPCClientOptions() []option.ClientOption {
	return []option.ClientOption{
		internaloption.WithDefaultEndpoint("grpc.domain.com:50051"),
		internaloption.WithDefaultEndpointTemplate("grpc.domain.com:50051"),
		internaloption.WithDefaultMTLSEndpoint("grpc.domain.com:50051"),
		internaloption.WithDefaultUniverseDomain("googleapis.com"),
		internaloption.WithDefaultAudience("https://grpc.domain.com/"),
		internaloption.WithDefaultScopes(DefaultAuthScopes()...),
		internaloption.EnableJwtWithScope(),
		internaloption.EnableNewAuthLibrary(),
		option.WithGRPCDialOption(grpc.WithDefaultCallOptions(
		grpc.MaxCallRecvMsgSize(math.MaxInt32))),
	}
}

func defaultEchoServerCallOptions() *EchoServerCallOptions {
	return &EchoServerCallOptions{
		SayHello: []gax.CallOption{
			gax.WithTimeout(600000 * time.Millisecond),
			gax.WithRetry(func() gax.Retryer {
				return gax.OnCodes([]codes.Code{
					codes.Unknown,
					codes.Unavailable,
				}, gax.Backoff{
					Initial:    200 * time.Millisecond,
					Max:        60000 * time.Millisecond,
					Multiplier: 1.30,
				})
			}),
		},
		SayHelloLRO: []gax.CallOption{
			gax.WithTimeout(600000 * time.Millisecond),
			gax.WithRetry(func() gax.Retryer {
				return gax.OnCodes([]codes.Code{
					codes.Unknown,
					codes.Unavailable,
				}, gax.Backoff{
					Initial:    200 * time.Millisecond,
					Max:        60000 * time.Millisecond,
					Multiplier: 1.30,
				})
			}),
		},
	}
}

// internalEchoServerClient is an interface that defines the methods available from .
type internalEchoServerClient interface {
	Close() error
	setGoogleClientInfo(...string)
	Connection() *grpc.ClientConn
	SayHello(context.Context, *echopb.EchoRequest, ...gax.CallOption) (*echopb.EchoReply, error)
	SayHelloLRO(context.Context, *echopb.EchoRequest, ...gax.CallOption) (*SayHelloLROOperation, error)
	SayHelloLROOperation(name string) *SayHelloLROOperation
}

// EchoServerClient is a client for interacting with .
// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
type EchoServerClient struct {
	// The internal transport-dependent client.
	internalClient internalEchoServerClient

	// The call options for this service.
	CallOptions *EchoServerCallOptions

	// LROClient is used internally to handle long-running operations.
	// It is exposed so that its CallOptions can be modified if required.
	// Users should not Close this client.
	LROClient *lroauto.OperationsClient

}

// Wrapper methods routed to the internal client.

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *EchoServerClient) Close() error {
	return c.internalClient.Close()
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *EchoServerClient) setGoogleClientInfo(keyval ...string) {
	c.internalClient.setGoogleClientInfo(keyval...)
}

// Connection returns a connection to the API service.
//
// Deprecated: Connections are now pooled so this method does not always
// return the same resource.
func (c *EchoServerClient) Connection() *grpc.ClientConn {
	return c.internalClient.Connection()
}

func (c *EchoServerClient) SayHello(ctx context.Context, req *echopb.EchoRequest, opts ...gax.CallOption) (*echopb.EchoReply, error) {
	return c.internalClient.SayHello(ctx, req, opts...)
}

func (c *EchoServerClient) SayHelloLRO(ctx context.Context, req *echopb.EchoRequest, opts ...gax.CallOption) (*SayHelloLROOperation, error) {
	return c.internalClient.SayHelloLRO(ctx, req, opts...)
}

// SayHelloLROOperation returns a new SayHelloLROOperation from a given name.
// The name must be that of a previously created SayHelloLROOperation, possibly from a different process.
func (c *EchoServerClient) SayHelloLROOperation(name string) *SayHelloLROOperation {
	return c.internalClient.SayHelloLROOperation(name)
}

// echoServerGRPCClient is a client for interacting with  over gRPC transport.
//
// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
type echoServerGRPCClient struct {
	// Connection pool of gRPC connections to the service.
	connPool gtransport.ConnPool

	// Points back to the CallOptions field of the containing EchoServerClient
	CallOptions **EchoServerCallOptions

	// The gRPC API client.
	echoServerClient echopb.EchoServerClient

	// LROClient is used internally to handle long-running operations.
	// It is exposed so that its CallOptions can be modified if required.
	// Users should not Close this client.
	LROClient **lroauto.OperationsClient

	// The x-goog-* metadata to be sent with each request.
	xGoogHeaders []string

	logger *slog.Logger
}

// NewEchoServerClient creates a new echo server client based on gRPC.
// The returned client must be Closed when it is done being used to clean up its underlying connections.
func NewEchoServerClient(ctx context.Context, opts ...option.ClientOption) (*EchoServerClient, error) {
	clientOpts := defaultEchoServerGRPCClientOptions()
	if newEchoServerClientHook != nil {
		hookOpts, err := newEchoServerClientHook(ctx, clientHookParams{})
		if err != nil {
			return nil, err
		}
		clientOpts = append(clientOpts, hookOpts...)
	}

	connPool, err := gtransport.DialPool(ctx, append(clientOpts, opts...)...)
	if err != nil {
		return nil, err
	}
	client := EchoServerClient{CallOptions: defaultEchoServerCallOptions()}

	c := &echoServerGRPCClient{
		connPool:    connPool,
		echoServerClient: echopb.NewEchoServerClient(connPool),
		CallOptions: &client.CallOptions,
		logger: internaloption.GetLogger(opts),

	}
	c.setGoogleClientInfo()

	client.internalClient = c

	client.LROClient, err = lroauto.NewOperationsClient(ctx, gtransport.WithConnPool(connPool))
	if err != nil {
		// This error "should not happen", since we are just reusing old connection pool
		// and never actually need to dial.
		// If this does happen, we could leak connp. However, we cannot close conn:
		// If the user invoked the constructor with option.WithGRPCConn,
		// we would close a connection that's still in use.
		// TODO: investigate error conditions.
		return nil, err
	}
	c.LROClient = &client.LROClient
	return &client, nil
}

// Connection returns a connection to the API service.
//
// Deprecated: Connections are now pooled so this method does not always
// return the same resource.
func (c *echoServerGRPCClient) Connection() *grpc.ClientConn {
	return c.connPool.Conn()
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *echoServerGRPCClient) setGoogleClientInfo(keyval ...string) {
	kv := append([]string{"gl-go", gax.GoVersion}, keyval...)
	kv = append(kv, "gapic", getVersionClient(), "gax", gax.Version, "grpc", grpc.Version)
	c.xGoogHeaders = []string{
		"x-goog-api-client", gax.XGoogHeader(kv...),
	}
}

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *echoServerGRPCClient) Close() error {
	return c.connPool.Close()
}

func (c *echoServerGRPCClient) SayHello(ctx context.Context, req *echopb.EchoRequest, opts ...gax.CallOption) (*echopb.EchoReply, error) {
	hds := []string{"x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName()))}

	hds = append(c.xGoogHeaders, hds...)
	ctx = gax.InsertMetadataIntoOutgoingContext(ctx, hds...)
	opts = append((*c.CallOptions).SayHello[0:len((*c.CallOptions).SayHello):len((*c.CallOptions).SayHello)], opts...)
	var resp *echopb.EchoReply
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = executeRPC(ctx, c.echoServerClient.SayHello, req, settings.GRPC, c.logger, "SayHello")
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *echoServerGRPCClient) SayHelloLRO(ctx context.Context, req *echopb.EchoRequest, opts ...gax.CallOption) (*SayHelloLROOperation, error) {
	hds := []string{"x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName()))}

	hds = append(c.xGoogHeaders, hds...)
	ctx = gax.InsertMetadataIntoOutgoingContext(ctx, hds...)
	opts = append((*c.CallOptions).SayHelloLRO[0:len((*c.CallOptions).SayHelloLRO):len((*c.CallOptions).SayHelloLRO)], opts...)
	var resp *longrunningpb.Operation
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = executeRPC(ctx, c.echoServerClient.SayHelloLRO, req, settings.GRPC, c.logger, "SayHelloLRO")
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return &SayHelloLROOperation{
		lro: longrunning.InternalNewOperation(*c.LROClient, resp),
	}, nil
}

// SayHelloLROOperation returns a new SayHelloLROOperation from a given name.
// The name must be that of a previously created SayHelloLROOperation, possibly from a different process.
func (c *echoServerGRPCClient) SayHelloLROOperation(name string) *SayHelloLROOperation {
	return &SayHelloLROOperation{
		lro: longrunning.InternalNewOperation(*c.LROClient, &longrunningpb.Operation{Name: name}),
	}
}
