// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go_gapic. DO NOT EDIT.

package echoclient_test

import (
	"context"
	echopb "echo"
	echoclient "echoclient"
)

func ExampleNewEchoServerClient() {
	ctx := context.Background()
	c, err := echoclient.NewEchoServerClient(ctx)
	if err != nil {
		// TODO: Handle error.
	}
	// TODO: Use client.
	_ = c
}

func ExampleEchoServerClient_SayHello() {
	// import echopb "echo"

	ctx := context.Background()
	c, err := echoclient.NewEchoServerClient(ctx)
	if err != nil {
		// TODO: Handle error.
	}

	req := &echopb.EchoRequest{
		// TODO: Fill request struct fields.
	}
	resp, err := c.SayHello(ctx, req)
	if err != nil {
		// TODO: Handle error.
	}
	// TODO: Use resp.
	_ = resp
}

func ExampleEchoServerClient_SayHelloLRO() {
	// import echopb "echo"

	ctx := context.Background()
	c, err := echoclient.NewEchoServerClient(ctx)
	if err != nil {
		// TODO: Handle error.
	}

	req := &echopb.EchoRequest{
		// TODO: Fill request struct fields.
	}
	op, err := c.SayHelloLRO(ctx, req)
	if err != nil {
		// TODO: Handle error.
	}

	resp, err := op.Wait(ctx)
	if err != nil {
		// TODO: Handle error.
	}
	// TODO: Use resp.
	_ = resp
}
